// src/services/retrieval.service.js

import { GoogleGenAI } from "@google/genai";
import { getAllKnowledgeChunks } from "../repositories/knowledge.repository.js";
import { cosineSimilarity } from "../utils/similarity.js";
import { env } from "../config/env.js";

const ai = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });

const TOP_K = 4; // how many chunks to retrieve per question

export async function retrieveRelevantChunks(question) {
  // Embed the incoming question using the same model used to embed
  // the knowledge base — comparing vectors only makes sense if both
  // sides were generated by the same embedding model.
  const questionEmbeddingResponse = await ai.models.embedContent({
    model: "gemini-embedding-001",
    contents: question,
  });
  const questionVector = questionEmbeddingResponse.embeddings[0].values;

  const chunks = await getAllKnowledgeChunks();

  const scored = chunks.map((chunk) => ({
    ...chunk,
    score: cosineSimilarity(questionVector, chunk.embedding),
  }));

  // Highest similarity first, keep only the top matches — these are
  // the chunks most relevant to what was actually asked.
  scored.sort((a, b) => b.score - a.score);

  return scored.slice(0, TOP_K);
}
